config/routes.rb
Datatable::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users

  resources :anagraficas

   root :to => "rails_admin/main#dashboard"

end

app/models/anagrafica.rb
class Anagrafica < ActiveRecord::Base

  image_accessor :allegato_test_book do
    storage_opts do |a|
      {
        :path => "esame_requisiti/#{allegato_test_book_name}",
        :other => 'option'
      }
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/anagraficas_controller.rb
class AnagraficasController < ApplicationController
  # GET /anagraficas
  # GET /anagraficas.json
  def index
    @anagraficas = Anagrafica.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @anagraficas }
    end
  end

  # GET /anagraficas/1
  # GET /anagraficas/1.json
  def show
    @anagrafica = Anagrafica.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @anagrafica }
    end
  end

  # GET /anagraficas/new
  # GET /anagraficas/new.json
  def new
    @anagrafica = Anagrafica.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @anagrafica }
    end
  end

  # GET /anagraficas/1/edit
  def edit
    @anagrafica = Anagrafica.find(params[:id])
  end

  # POST /anagraficas
  # POST /anagraficas.json
  def create
    @anagrafica = Anagrafica.new(params[:anagrafica])

    respond_to do |format|
      if @anagrafica.save
        UserMailer.welcome_email(@anagrafica).deliver
        format.html { redirect_to @anagrafica, notice: 'Anagrafica was successfully created.' }
        format.json { render json: @anagrafica, status: :created, location: @anagrafica }
      else
        format.html { render action: "new" }
        format.json { render json: @anagrafica.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /anagraficas/1
  # PUT /anagraficas/1.json
  def update
    @anagrafica = Anagrafica.find(params[:id])

    respond_to do |format|
      if @anagrafica.update_attributes(params[:anagrafica])
        format.html { redirect_to @anagrafica, notice: 'Anagrafica was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @anagrafica.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /anagraficas/1
  # DELETE /anagraficas/1.json
  def destroy
    @anagrafica = Anagrafica.find(params[:id])
    @anagrafica.destroy

    respond_to do |format|
      format.html { redirect_to anagraficas_url }
      format.json { head :ok }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
   protect_from_forgery
  before_filter :authenticate_user!

  layout :layout_by_resource
  def layout_by_resource
    if devise_controller?
      "sign"
    else
      "application"
    end
  end

end

app/helpers/anagraficas_helper.rb
module AnagraficasHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/anagraficas/_form.html.erb
<%= form_for(@anagrafica) do |f| %>
  <% if @anagrafica.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@anagrafica.errors.count, "error") %> prohibited this anagrafica from being saved:</h2>

      <ul>
      <% @anagrafica.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
<div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
<div class="field">
    <%= f.label :login %><br />
    <%= f.text_field :login %>
  </div>
  <div class="field">
    <%= f.label :data %><br />
    <%= f.date_select :data %>
  </div>
  <div class="field">
    <%= f.label :indirizzo %><br />
    <%= f.text_field :indirizzo %>
  </div>
  <div class="field">
    <%= f.label :citta %><br />
    <%= f.text_field :citta %>
  </div>
<div class="group">
    <%= f.label :allegato_test_book, t("activerecord.attributes.summary_requirement.cover_image", :default => "Inserisci Allegato"), :class => :label %>
    <%= f.file_field :allegato_test_book %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/anagraficas/edit.html.erb
<h1>Editing anagrafica</h1>

<%= render 'form' %>

<%= link_to 'Show', @anagrafica %> |
<%= link_to 'Back', anagraficas_path %>

app/views/anagraficas/index.html.erb
<h1>Listing anagraficas</h1>

<table id="anagraficas" class="display">
  <thead
  <tr>
    <th>Nome</th>
    <th>Email</th>
    <th>Login</th>
    <th>Data</th>
    <th>Indirizzo</th>
    <th>Citta</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>
<tbody>
<% @anagraficas.each do |anagrafica| %>
  <tr>
    <td><%= anagrafica.nome %></td>
     <td><%= anagrafica.email %></td>
      <td><%= anagrafica.login %></td>
    <td><%= anagrafica.data %></td>
    <td><%= anagrafica.indirizzo %></td>
    <td><%= anagrafica.citta %></td>
    <td><%= link_to 'Show', anagrafica %></td>
    <td><%= link_to 'Edit', edit_anagrafica_path(anagrafica) %></td>
    <td><%= link_to 'Destroy', anagrafica, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</tbody>
</table>

<br />

<%= link_to 'New Anagrafica', new_anagrafica_path %>

app/views/anagraficas/new.html.erb
<h1>New anagrafica</h1>

<%= render 'form' %>

<%= link_to 'Back', anagraficas_path %>

app/views/anagraficas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @anagrafica.nome %>
</p>
<p>
  <b>Email:</b>
  <%= @anagrafica.email %>
</p>
<p>
  <b>Login:</b>
  <%= @anagrafica.login %>
</p>

<p>
  <b>Data:</b>
  <%= @anagrafica.data %>
</p>

<p>
  <b>Indirizzo:</b>
  <%= @anagrafica.indirizzo %>
</p>

<p>
  <b>Citta:</b>
  <%= @anagrafica.citta %>
</p>

<p>
         <b><%= t("activerecord.attributes.summary_requirement.allegato", :default => t("activerecord.labels.data", :default => "Allegato Inserito")) %>:</b>
        <%=  @anagrafica.allegato_test_book.name  if @anagrafica.allegato_test_book_uid %>|| <%=link_to "Visualizza Allegato",@anagrafica.allegato_test_book.url  if @anagrafica.allegato_test_book_uid%>
         </p>


<%= link_to 'Edit', edit_anagrafica_path(@anagrafica) %> |
<%= link_to 'Back', anagraficas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Datatable</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>

  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/sign.html.haml
!!!
%html
  %head
    %title Xen Informatica
    = stylesheet_link_tag :application
    = javascript_include_tag :application
    = csrf_meta_tag
  %body
    #container
      #box
        %div.block#block-login
          %h2 Svi-Webdesign Application
          %div.content.login
            = yield